// File generated by FlutterFire CLI.
// Patched manually for development - Update with your Firebase project config
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdU-IrwrDgedCarsSjk4OnGQaw_s2iF1Y',
    appId: '1:270975220033:web:0ea07ed752f844542749c0',
    messagingSenderId: '270975220033',
    projectId: 'tailoringapp-c768d',
    authDomain: 'tailoringapp-c768d.firebaseapp.com',
    storageBucket: 'tailoringapp-c768d.firebasestorage.app',
    measurementId: 'G-4LP3KFSN9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-api-key-android',
    appId: '1:demo-android-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'your-demo-project',
    storageBucket: 'demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-api-key-ios',
    appId: '1:demo-ios-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'your-demo-project',
    storageBucket: 'demo-project.appspot.com',
    iosBundleId: 'com.example.tailoringapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key-macos',
    appId: '1:demo-macos-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'your-demo-project',
    storageBucket: 'demo-project.appspot.com',
    iosBundleId: 'com.example.tailoringapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-api-key-windows',
    appId: '1:demo-windows-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'your-demo-project',
    storageBucket: 'demo-project.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'demo-api-key-linux',
    appId: '1:demo-linux-app-id',
    messagingSenderId: 'demo-sender-id',
    projectId: 'your-demo-project',
    storageBucket: 'demo-project.appspot.com',
  );
}
